main-job:
  image: ubuntu:trusty
  script:
    #  Set up third-party repositories
    - sudo apt-get update -qq && sudo apt-get -y install software-properties-common    # https://askubuntu.com/a/639431
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x                         # https://askubuntu.com/a/610352
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test                           # https://askubuntu.com/a/581497
    - sudo add-apt-repository -y ppa:beineri/opt-qt593-trusty                          # https://gitlab.com/probono/QtQuickApp/blob/master/.gitlab-ci.yml
    - sudo apt update -qq

    # Install needed packages and set up development environment
    - sudo apt install -y cmake build-essential gcc-6 g++-6 qt59base libqt5x11extras5-dev
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
    - . /opt/qt*/bin/qt*-env.sh || true

    # Build application
    - mkdir build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - make -j$(nproc)

    # Run tests
    - ./bow-simulator-test
