build-linux:
  image: ubuntu:trusty
  script:
    #  Set up third-party repositories
    - apt update -qq && apt install -y software-properties-common    # add-apt-repository, https://askubuntu.com/a/639431
    - add-apt-repository -y ppa:george-edison55/cmake-3.x            # cmake, https://askubuntu.com/a/610352
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test              # gcc-6, https://askubuntu.com/a/581497
    - add-apt-repository -y ppa:beineri/opt-qt593-trusty             # qt5.9, https://gitlab.com/probono/QtQuickApp/blob/master/.gitlab-ci.yml
    - apt update -qq

    # Install necessary packages and set up development environment
    - apt install -y wget fuse cmake make dpkg gcc-6 g++-6 qt59base qt59x11extras libgl1-mesa-dev
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
    - . /opt/qt*/bin/qt*-env.sh || true

    # Build application
    - mkdir build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Release
    - make -j$(nproc)

    # Run tests
    - ./bow-simulator-test

    # Build AppImage
    - wget -O /usr/local/bin/linuxdeployqt "https://github.com/probonopd/linuxdeployqt/releases/download/5/linuxdeployqt-5-x86_64.AppImage"
    - chmod a+x /usr/local/bin/linuxdeployqt
    - make appimage
    
    # Build deb-package
    - make deb-package
    
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.deb
