jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.1/windows-mingw_64.zip && 7z x windows-mingw_64.zip
      cmake ../ -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=windows-mingw_64/paths.cmake
      cmake --build .
      ./virtualbow-test
      cmake --build . --target iss-installer
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'Windows_Artifacts'

- job: MacOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      npm install -g appdmg@0.5.2
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.1/macos-clang_64.zip && unzip macos-clang_64.zip
      cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=macos-clang_64/paths.cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11
      cmake --build .
      ./virtualbow-test
      cmake --build . --target dmg-installer
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'MacOS_Artifacts'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    CC: gcc-9
    CXX: g++-9
  steps:
  - script: |
      sudo apt update -qq && sudo apt install -y libgl1-mesa-dev
      mkdir build && cd build
      curl -LO https://github.com/bow-simulation/virtualbow-dependencies/releases/download/v1.1/linux-gcc_64.zip && unzip linux-gcc_64.zip
      cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=linux-gcc_64/paths.cmake
      cmake --build .
      ./virtualbow-test
      cmake --build . --target deb-package
      cmake --build . --target rpm-package
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'build/packages'
      artifactName: 'Linux_Artifacts'